# Generated by Django 4.1.3 on 2022-11-14 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gross_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(blank=True, choices=[(None, 'None'), ('initiated', 'ACH Initiated'), ('returned', 'ACH Returned'), ('authorized', 'ACH Authorized'), ('successful', 'Successful'), ('cancelled', 'Cancelled')], default=None, max_length=15, null=True)),
                ('customer', models.CharField(default='', max_length=255)),
                ('swifter_id', models.CharField(default='', max_length=6)),
                ('external_id', models.CharField(default='', max_length=6)),
                ('source', models.CharField(blank=True, choices=[(None, 'None'), ('payments', 'Payments'), ('ecommerce', 'E-commerce'), ('instore', 'In-Store')], default=None, max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
            },
        ),
    ]
